### ISSUE TITLE
Old dependencies.

### ISSUE THREAD

**Issue by KidusMT** [chkal/todo-mvc#5]
Some of the dependencies have depreciated and not working. Here are some on the `pom.xml` file:

```xml
<dependency>
      <groupId>javax.mvc</groupId>
      <artifactId>javax.mvc-api</artifactId>
      <version>20160715</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.ozark</groupId>
      <artifactId>ozark</artifactId>
      <version>20160715</version>
    </dependency>

    <!-- This example uses JSP as the view technology -->
    <dependency>
      <groupId>javax.servlet-api</groupId>
      <artifactId>jstl</artifactId>
      <version>3.0-alpha-1</version>
    </dependency>
```

tried to replace them with:
```xml
<dependency>
      <groupId>javax.mvc</groupId>
      <artifactId>javax.mvc-api</artifactId>
      <version>1.0-edr1</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.glassfish.ozark</groupId>
      <artifactId>ozark</artifactId>
      <version>1.0.0-m02</version>
    </dependency>

    <!-- This example uses JSP as the view technology -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
```
pulling the new library seem to work but I am not sure if they are the correct libraries that I have added on the pom dependencies. And the classes on the java classes are not resolved. Marked red 🥺

I am new for spring mvc. Thank you.

**Comment by KidusMT** [comment]
updated the `javax.mvc` dependency with:

```xml
<!-- https://mvnrepository.com/artifact/javax.mvc/javax.mvc-api -->
<dependency>
    <groupId>javax.mvc</groupId>
    <artifactId>javax.mvc-api</artifactId>
    <version>1.0-pr</version>
    <scope>provided</scope>
</dependency>

```
 from : https://mvnrepository.com/artifact/javax.mvc/javax.mvc-api/1.0-pr

**Comment by chkal** [comment]
Hi! This project is a very old demo for MVC 1.0, which is NOT the same as Spring MVC.

I just updated the dependencies, and it compiles fine now. However, the app runs into some other issue which I won't have to fix now. Maybe at some later point.

However, if you are looking for a Spring MVC demo project, this repo is definitely not what you are looking for. :-)

**Comment by KidusMT** [comment]
Thanks so much @chkal I will check for your updates and see the project. But yes I think am gonna have to find another project for Spring MVC. I am just starting Spring technology. Appreciated!

**Comment by KidusMT** [comment]
Checked and it works well. 👍

only thing failing is when running. Not an issue for me but might be useful for another person checking it.

![image](https://user-images.githubusercontent.com/18373774/117578916-5023ec00-b0b6-11eb-9627-0d7333a36224.png)
